"""Anima Python SDK — official client for the Anima API."""

from ._client import Anima, AsyncAnima
from ._exceptions import (
    AnimaError,
    APIError,
    AuthenticationError,
    ConflictError,
    InternalServerError,
    NotFoundError,
    RateLimitError,
    ValidationError,
)
from ._types import (
    # A2A (Agent-to-Agent Protocol)
    A2AArtifact,
    A2ATaskOutput,
    A2ATaskStatus,
    AddressOutput,
    AddressType,
    AgentCardOutput,
    AgentOutput,
    AgentStatus,
    AnimaEvent,
    ApprovalList,
    ApprovalStatus,
    AttachmentDownloadOutput,
    AttachmentOutput,
    Card,
    CardApproval,
    CardList,
    CardStatus,
    CardTransaction,
    CardType,
    CredentialType,
    CursorPagination,
    DateRange,
    DeliverabilityStatsOutput,
    DidDocument,
    DidRotateOutput,
    DomainDnsRecord,
    DomainDnsRecordsOutput,
    DomainDnsRecordWithPriority,
    DomainMailFromConfig,
    DomainOutput,
    DomainRecordStatus,
    DomainStatus,
    DomainStatusRecord,
    DomainZoneFileOutput,
    EmailIdentityOutput,
    KillSwitchResult,
    MessageChannel,
    MessageDirection,
    MessageOutput,
    MessageStatus,
    OrganizationOutput,
    PaginatedResponse,
    PhoneCapabilities,
    PhoneIdentityOutput,
    PhoneProvider,
    PhoneProvisionOutput,
    PodOutput,
    PodResourceSpec,
    PodStatus,
    PodUsageOutput,
    PolicyAction,
    RegistryAgentOutput,
    SecurityEventOutput,
    SecurityEventType,
    SecurityScanOutput,
    SecurityScanWarning,
    SecuritySeverity,
    SpendingPolicy,
    TenDlcStatus,
    Tier,
    TransactionList,
    TransactionStatus,
    ValidateAddressOutput,
    VaultCardData,
    VaultCredential,
    VaultCustomField,
    VaultCustomFieldType,
    VaultIdentityData,
    VaultIdentityOutput,
    VaultLoginData,
    VaultLoginUri,
    VaultStatusOutput,
    VaultTotpOutput,
    VerifiableCredential,
    VerificationMethod,
    VerifyCredentialOutput,
    WalletOutput,
    WalletPayOutput,
    WalletStatus,
    WalletTransactionOutput,
    WebhookDeliveryOutput,
    WebhookEvent,
    WebhookEventType,
    WebhookOutput,
    WebhookTestOutput,
    X402FetchOutput,
    # Voice / Calls
    CallDirection,
    CallOutput,
    CallTranscript,
    CreateCallOutput,
    TranscriptSegment,
    Voice,
    VoiceGender,
    VoiceProvider,
    VoiceTier,
)
from ._http import RawResponse, RequestEvent, RequestOptions, ResponseEvent
from ._middleware import fastapi_webhook_dependency
from ._pagination import AsyncPageIterator, SyncPageIterator
from ._webhooks import construct_webhook_event, verify_webhook_signature
from .resources.events import AsyncEventsResource, AsyncEventStream, EventsResource, EventStream

__all__ = [
    # Clients
    "Anima",
    "AsyncAnima",
    # Errors
    "AnimaError",
    "APIError",
    "AuthenticationError",
    "ConflictError",
    "InternalServerError",
    "NotFoundError",
    "RateLimitError",
    "ValidationError",
    # Webhook helpers
    "verify_webhook_signature",
    "construct_webhook_event",
    # Enums
    "AddressType",
    "AgentStatus",
    "ApprovalStatus",
    "CardStatus",
    "CardType",
    "CredentialType",
    "DomainRecordStatus",
    "DomainStatus",
    "MessageChannel",
    "MessageDirection",
    "MessageStatus",
    "PhoneProvider",
    "PolicyAction",
    "SecurityEventType",
    "SecuritySeverity",
    "TenDlcStatus",
    "Tier",
    "TransactionStatus",
    "VaultCustomFieldType",
    "VerificationMethod",
    "CallDirection",
    "VoiceGender",
    "VoiceProvider",
    "VoiceTier",
    "WebhookEventType",
    # Events (WebSocket)
    "AnimaEvent",
    "EventStream",
    "AsyncEventStream",
    "EventsResource",
    "AsyncEventsResource",
    # Models
    "AddressOutput",
    "AgentCardOutput",
    "AgentOutput",
    "ApprovalList",
    "AttachmentDownloadOutput",
    "AttachmentOutput",
    "Card",
    "CardApproval",
    "CardList",
    "CardTransaction",
    "CursorPagination",
    "DateRange",
    "DeliverabilityStatsOutput",
    "DidDocument",
    "DidRotateOutput",
    "DomainDnsRecord",
    "DomainDnsRecordsOutput",
    "DomainDnsRecordWithPriority",
    "DomainMailFromConfig",
    "DomainOutput",
    "DomainStatusRecord",
    "DomainZoneFileOutput",
    "EmailIdentityOutput",
    "KillSwitchResult",
    "MessageOutput",
    "OrganizationOutput",
    "PaginatedResponse",
    "PhoneCapabilities",
    "PhoneIdentityOutput",
    "PhoneProvisionOutput",
    "PodOutput",
    "PodResourceSpec",
    "PodStatus",
    "PodUsageOutput",
    "RegistryAgentOutput",
    "SecurityEventOutput",
    "SecurityScanOutput",
    "SecurityScanWarning",
    "SpendingPolicy",
    "TransactionList",
    "VaultCardData",
    "VaultCredential",
    "VaultCustomField",
    "VaultIdentityData",
    "VaultIdentityOutput",
    "VaultLoginData",
    "VaultLoginUri",
    "VaultStatusOutput",
    "ValidateAddressOutput",
    "VaultTotpOutput",
    "VerifiableCredential",
    "VerifyCredentialOutput",
    "WalletOutput",
    "WalletPayOutput",
    "WalletStatus",
    "WalletTransactionOutput",
    "WebhookDeliveryOutput",
    "WebhookEvent",
    "WebhookOutput",
    "WebhookTestOutput",
    "X402FetchOutput",
    # Voice / Calls
    "CallOutput",
    "CallTranscript",
    "CreateCallOutput",
    "TranscriptSegment",
    "Voice",
    # A2A (Agent-to-Agent Protocol)
    "A2AArtifact",
    "A2ATaskOutput",
    "A2ATaskStatus",
    # Pagination
    "SyncPageIterator",
    "AsyncPageIterator",
    # Request options
    "RequestOptions",
    "RawResponse",
    # Events
    "RequestEvent",
    "ResponseEvent",
    # Middleware
    "fastapi_webhook_dependency",
]
