"""Anima Python SDK — official client for the Anima API."""

from ._client import Anima, AsyncAnima
from ._exceptions import (
    AnimaError,
    APIError,
    AuthenticationError,
    ConflictError,
    InternalServerError,
    NotFoundError,
    RateLimitError,
    ValidationError,
)
from ._http import RawResponse, RequestEvent, RequestOptions, ResponseEvent
from ._middleware import fastapi_webhook_dependency
from ._pagination import AsyncPageIterator, SyncPageIterator
from ._types import (
    # A2A (Agent-to-Agent Protocol)
    A2AArtifact,
    A2ATaskOutput,
    A2ATaskStatus,
    AddressOutput,
    AddressType,
    AgentCardOutput,
    AgentOutput,
    AgentStatus,
    AiScannerStatus,
    AnimaEvent,
    AttachmentDownloadOutput,
    AttachmentOutput,
    # Voice / Calls
    CallDirection,
    CallOutput,
    CallTranscript,
    # Compliance. Every value is SCREAMING_SNAKE because that is what the API
    # validates against; they shipped lowercase once and every compliance
    # request 400'd. Exported so callers can pass them by name instead of
    # retyping a string the API will silently reject.
    ComplianceControlCategory,
    ComplianceControlStatus,
    ComplianceFramework,
    ComplianceReportFormat,
    ComplianceReportStatus,
    ComplianceReportType,
    ConnectExtensionResult,
    CreateCallOutput,
    CredentialRequestStatus,
    CredentialType,
    CursorPagination,
    DateRange,
    DeliverabilityStatsOutput,
    DidDocument,
    DidRotateOutput,
    DomainDnsRecord,
    DomainDnsRecordsOutput,
    DomainDnsRecordWithPriority,
    DomainMailFromConfig,
    DomainOutput,
    DomainRecordStatus,
    DomainStatus,
    DomainStatusRecord,
    DomainZoneFileOutput,
    DsarStatus,
    DsarType,
    EmailDraftOutput,
    EmailIdentityOutput,
    InboxOutput,
    MessageChannel,
    MessageDirection,
    MessageOutput,
    MessageStatus,
    OrganizationOutput,
    PaginatedResponse,
    PhoneCapabilities,
    PhoneIdentityOutput,
    PhoneProvider,
    PhoneProvisionOutput,
    PolicyAction,
    RegistryAgentOutput,
    RevealPolicy,
    ScannerStatusOutput,
    SecurityEventOutput,
    SecurityEventType,
    SecuritySeverity,
    SemanticSearchResult,
    TenDlcStatus,
    Tier,
    TranscriptSegment,
    UseCredentialOutput,
    ValidateAddressOutput,
    VaultApiKeyData,
    VaultAuditLogEntry,
    VaultCardData,
    VaultCertificateData,
    VaultCredential,
    VaultCredentialRequest,
    VaultCredentialRequestCancelResult,
    VaultCredentialRequestListItem,
    VaultCredentialRequestStatusOutput,
    VaultCustomField,
    VaultCustomFieldType,
    VaultIdentityData,
    VaultIdentityListItem,
    VaultIdentityOutput,
    VaultLoginData,
    VaultLoginUri,
    VaultOAuthTokenData,
    VaultRateLimit,
    VaultStatusOutput,
    VaultTotpOutput,
    VerifiableCredentialRecord,
    VerifiableCredentialType,
    VerificationMethod,
    VerifyCredentialOutput,
    Voice,
    VoiceGender,
    VoiceTier,
    WebhookAuthBasic,
    WebhookAuthBearer,
    WebhookAuthConfig,
    WebhookAuthCustomHeader,
    WebhookAuthNone,
    WebhookDeliveryOutput,
    WebhookEvent,
    WebhookEventType,
    WebhookOutput,
    WebhookTestOutput,
)
from ._voice_connection import VoiceConnection
from ._webhooks import construct_webhook_event, verify_webhook_signature
from .resources.events import AsyncEventsResource, AsyncEventStream, EventsResource, EventStream

__all__ = [
    # Clients
    "Anima",
    "AsyncAnima",
    # Errors
    "AnimaError",
    "APIError",
    "AuthenticationError",
    "ConflictError",
    "InternalServerError",
    "NotFoundError",
    "RateLimitError",
    "ValidationError",
    # Webhook helpers
    "verify_webhook_signature",
    "construct_webhook_event",
    # Enums
    "AddressType",
    "AgentStatus",
    "ComplianceControlCategory",
    "ComplianceControlStatus",
    "ComplianceFramework",
    "ComplianceReportFormat",
    "ComplianceReportStatus",
    "ComplianceReportType",
    "CredentialRequestStatus",
    "CredentialType",
    "DomainRecordStatus",
    "DomainStatus",
    "DsarStatus",
    "DsarType",
    "MessageChannel",
    "MessageDirection",
    "MessageStatus",
    "PhoneProvider",
    "PolicyAction",
    "RevealPolicy",
    "SecurityEventType",
    "SecuritySeverity",
    "TenDlcStatus",
    "Tier",
    "VaultCustomFieldType",
    "VerificationMethod",
    "CallDirection",
    "VoiceGender",
    "VoiceTier",
    "WebhookEventType",
    # Events (WebSocket)
    "AnimaEvent",
    "EventStream",
    "AsyncEventStream",
    "EventsResource",
    "AsyncEventsResource",
    # Models
    "AddressOutput",
    "AgentCardOutput",
    "AiScannerStatus",
    "AgentOutput",
    "AttachmentDownloadOutput",
    "AttachmentOutput",
    "ConnectExtensionResult",
    "CursorPagination",
    "DateRange",
    "DeliverabilityStatsOutput",
    "DidDocument",
    "DidRotateOutput",
    "DomainDnsRecord",
    "DomainDnsRecordsOutput",
    "DomainDnsRecordWithPriority",
    "DomainMailFromConfig",
    "DomainOutput",
    "DomainStatusRecord",
    "DomainZoneFileOutput",
    "EmailDraftOutput",
    "EmailIdentityOutput",
    "InboxOutput",
    "MessageOutput",
    "OrganizationOutput",
    "PaginatedResponse",
    "PhoneCapabilities",
    "PhoneIdentityOutput",
    "PhoneProvisionOutput",
    "RegistryAgentOutput",
    "SecurityEventOutput",
    "ScannerStatusOutput",
    "SemanticSearchResult",
    "VaultApiKeyData",
    "VaultAuditLogEntry",
    "VaultCardData",
    "VaultCertificateData",
    "VaultCredential",
    "VaultCredentialRequest",
    "VaultCredentialRequestCancelResult",
    "VaultCredentialRequestListItem",
    "VaultCredentialRequestStatusOutput",
    "UseCredentialOutput",
    "VaultCustomField",
    "VaultIdentityData",
    "VaultIdentityListItem",
    "VaultIdentityOutput",
    "VaultLoginData",
    "VaultLoginUri",
    "VaultOAuthTokenData",
    "VaultRateLimit",
    "VaultStatusOutput",
    "ValidateAddressOutput",
    "VaultTotpOutput",
    "VerifiableCredentialRecord",
    "VerifiableCredentialType",
    "VerifyCredentialOutput",
    "WebhookAuthBasic",
    "WebhookAuthBearer",
    "WebhookAuthConfig",
    "WebhookAuthCustomHeader",
    "WebhookAuthNone",
    "WebhookDeliveryOutput",
    "WebhookEvent",
    "WebhookOutput",
    "WebhookTestOutput",
    # Voice / Calls
    "CallOutput",
    "CallTranscript",
    "CreateCallOutput",
    "TranscriptSegment",
    "Voice",
    "VoiceConnection",
    # A2A (Agent-to-Agent Protocol)
    "A2AArtifact",
    "A2ATaskOutput",
    "A2ATaskStatus",
    # Pagination
    "SyncPageIterator",
    "AsyncPageIterator",
    # Request options
    "RequestOptions",
    "RawResponse",
    # Events
    "RequestEvent",
    "ResponseEvent",
    # Middleware
    "fastapi_webhook_dependency",
]
